### ISSUE TITLE
How would compilation on playground work?

### ISSUE THREAD

**Issue by SlothScript** [ruthenium-lang/ruthenium#4]
As the name suggests. I am working on building the playground to execute the code, but how exactly would compiling it work? Should the playground compile byte code and interpret that, fully interpret, or compile and run on somebodies machine? For now I will work on python-like compilation.

**Comment by CiroZDP** [comment]
Hi. TYSM for contributing. The playground is going to be interpreted but i have planned this to have a compiler.

First everythings goes through a lexer or tokenizer (its already completed). To try the tokenizer host the playground in localhost and open the developer console and write this:
```let stream = new CodeStream('fn main() { println("Hello world"); }```
That line of code is going to create the code stream which is used by the tokenizer to do is job faster and easier.
Now lets tokenize it:
```qrtTokenize(stream);```

(Btw all the compiler api has the qrt prefix because this is the Q edition of the RuThenium interpreter, you can use another letter if you want)

The tokenizer will return a array of strings which are the tokens

**Comment by SlothScript** [comment]
Yeah I forked it and noticed the tokenizer

**Comment by CiroZDP** [comment]
So the next part is the AST Tree parser. This is not made yet. It analyzes the tokens and gives a JSON which indicates how the program behaves. Something like this but in JSON:
```yaml
functionDeclaration:
    name: "main"
    args: []
    body:
        functionCall:
            target: "println"
            args: ["Hello, world"]
```

**Comment by SlothScript** [comment]
Hey, I've started work on building the AST Tree from the parsed code; Could you provide the full possibly tree? Maybe give an example code with all the possible things and then the AST Tree. So far I have came up with a process for converting it, I just haven't put it into code. Thanks!

**Comment by SlothScript** [comment]
Oh I looked at the wikipedia page for the AST Tree and I understand it a bit better. I'll use the docs to figure out the possible things.

**Comment by CiroZDP** [comment]
Ok. Anything you need to ask me im here. By the way do you have discord?

**Comment by SlothScript** [comment]
I believe so, I just turned 13 and I don't remember if I created an account before I was

**Comment by SlothScript** [comment]
Yes I have discord

**Comment by CiroZDP** [comment]
May i get your username? Or you can send me the invite, the discord is in my github page.

**Comment by CiroZDP** [comment]
Hello world:
```yaml
functionDeclaration:
    name: "main"
    args: []
    body:
        functionCall:
            target: "println"
            args: ["Hello, world"]
```

---

Assignment
```rust
fn main() {
    let a: uint = 5;
}
```

Tree:
```yaml
functionDeclaration:
    name: "main"
    args: []
    body:
        varDeclaration:
            name: "a"
            type: "uint"
        varAssignment:
            target: "a"
            value: 5
            operator: "="
    
```
